---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cni-binary-copy-script
  namespace: kube-system
  annotations:
    kubernetes.io/description: |
      This is a script used to copy CNI binaries
data:
  cnibincopy.sh: |-
    #!/bin/bash
    cp -f /usr/src/plugins/bin/* /host/opt/cni/bin
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-containernetworking-plugins-ds-amd64
  namespace: kube-system
  labels:
    tier: node
    app: containernetworking-plugins
    name: containernetworking-plugins
spec:
  selector:
    matchLabels:
      name: containernetworking-plugins
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        app: containernetworking-plugins
        name: containernetworking-plugins
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/arch: amd64
      tolerations:
      - operator: Exists
        effect: NoSchedule
      initContainers:
      - name: containernetworking-binary-copy
        image: nfvpe/containernetworking-plugins
        command: ["/entrypoint/cnibincopy.sh"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: cni-binary-copy
          mountPath: /entrypoint
        - name: cnibin
          mountPath: /host/opt/cni/bin
      volumes:
        - name: cnibin
          hostPath:
            path: /opt/cni/bin
        - name: cni-binary-copy
          configMap:
            name: cni-binary-copy-script
            defaultMode: 0744
      containers:
      - name: kube-containernetworking-plugins
        image: busybox
        command: ["sleep"]
        args: ["infinity"]
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
